# Use this script to update all dependencies to the latest version and export them to requirements.txt.

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $true # might be true by default

# First, make sure that pwd is where the script is located
Set-Location $PSScriptRoot

# Remove preexisting .venv folder
if (Test-Path .\.venv) {
    Write-Host "Removing existing virtual environment..."
    Remove-Item .\.venv -Recurse -Force -ErrorAction SilentlyContinue
}

# Create a new virtual environment in the .venv folder
Write-Output "Creating a new virtual environment..."
py -m venv .venv

# Activate the virtual environment
Write-Output "Activating the virtual environment..."
& .\.venv\Scripts\Activate.ps1

# Install the package
Write-Output "Installing package (with dev dependencies)..."
pip install -e .[dev]

# Update pre-commit hooks
Write-Output "Updating pre-commit hooks..."
pre-commit autoupdate

# Export the installed packages to requirements.txt
Write-Output "Exporting installed packages to requirements.txt..."
Write-Output "# This file is automatically generated by freeze.ps1. Do not edit it manually." > requirements.txt
pip list --format freeze --exclude-editable >> requirements.txt
