Write-Output "This project uses ``Conventional Commits`` to manage its versioning, and a pre-commit hook enforces the commit message format."
Write-Output "The commit message format is: <type>(<optional scope>): <description>"
Write-Output "Where <type> is one of the following: feat, fix, docs, style, refactor, perf, test, build, ci, chore."
Write-Output "The <optional scope> is a noun describing a section of the codebase, and <description> is a short summary of the changes."
Write-Output "(Refer to https://www.conventionalcommits.org/ for more information.)"
Write-Output ""
Write-Output "The following scripts are available in this project:"
Write-Output "help.ps1         This script is used to provide help and usage information for the project."
Write-Output "freeze.ps1       This script is used to set up a virtual environment, update all dependencies to the latest version"
Write-Output "                 and export them to requirements.txt, and installs the pre-commit hooks."
Write-Output "install.ps1      This script is used to set up a virtual environment according to requirements.txt, and installs"
Write-Output "                 the pre-commit hooks."
Write-Output "new_version.ps1  This script uses ``python-semantic-release`` to create a changelog and increment the version number."
Write-Output ""
Write-Output "InteractiveHtmlBom is installed in the virtual environment. Run ``generate_interactive_bom --help`` for usage information."
