name: Release Artifacts

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.0.0, v2.1.3

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare release assets
      run: |
        mkdir release_assets
        cp release/altium-ibom-releaser.exe release_assets/
        cp InteractiveHTMLBOM4Altium2/InteractiveHTMLBOM4Altium2.pas release_assets/
        cp InteractiveHTMLBOM4Altium2/InteractiveHTMLBOM4Altium2.dfm release_assets/

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: release_assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
